name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build -f /docker/Dockerfile --no-cache -t avenga .
    - name: Start container
      run: docker run -v "${PWD}\allure-report:/app/allure-report" avenga:latest
    - name: Upload Fat JAR artifact
      uses: actions/upload-artifact@v4
      with:
        name: Report
        path: /app/allure-report/index.html
        retention-days: 1
