name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Build Fat JAR with Gradle
        run: ./gradlew clean fatJar
      - name: Upload Fat JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: fat-jar
          path: Avenga-all-1.0-SNAPSHOT-tests.jar
          retention-days: 1
      - name: Run tests
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'
      - name: Run fatjar
        run: java -jar Avenga-all-1.0-SNAPSHOT-tests.jar -testjar Avenga-all-1.0-SNAPSHOT-tests.jar -xmlpathinjar suite.xml
        continue-on-error: true
      - name: Generate allure
        run: allure generate --clean --single-file allure-results
      - name: Upload Allure report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: Allure-Report.html
          path: allure-report/index.html
          retention-days: 1