# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Build Fat JAR with Gradle
        run: ./gradlew clean fatJar
      - name: Upload Fat JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: fat-jar
          path: build/libs/*-SNAPSHOT.jar
          retention-days: 1
  runTest:
    runs-on: self-hosted
    steps:
      - name: Run tests
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'
      - name: Run fatjar
        run: java -jar Avenga-all-1.0-SNAPSHOT-tests.jar -testJar Avenga-all-1.0-SNAPSHOT-tests.jar
      - name: Generate allure
        run: allure generate --clean --single-file allure-results